trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: Terraform-Token

jobs:
  - job: dotnet
    displayName: "Build .NET"
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: UseDotNet@2
        displayName: "Install .NET Core SDK"
        inputs:
          packageType: sdk
          version: 8.x
          # installationPath: $(Agent.ToolsDirectory)/dotnet
      - task: DotNetCoreCLI@2
        displayName: "Publish"
        inputs:
          command: publish
          publishWebProjects: false
          projects: "**/*.csproj"
          arguments: "--configuration Release --output $(Build.ArtifactStagingDirectory)"
          zipAfterPublish: true
          modifyOutputPath: false
          workingDirectory: $(System.DefaultWorkingDirectory)/src

      - task: PublishPipelineArtifact@1
        displayName: "Publish Artifact"
        inputs:
          targetPath: $(Build.ArtifactStagingDirectory)
          artifact: drop
          publishLocation: pipeline
  
  - job: terraform
    displayName: "Terraform AzureRM 2.x"
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: echo "##vso[task.setvariable variable=TF_TOKEN_app_terraform_io]$(TF_TOKEN)"
        displayName: "Terraform Token"

      - script: ls -al
        displayName: "Script: List files"
        workingDirectory: $(System.DefaultWorkingDirectory)/v2

      - task: TerraformInstaller@2
        displayName: "Terraform: Installer"
        inputs:
          terraformVersion: "latest"

      - task: TerraformCLI@2
        displayName: "Terraform: init"
        inputs:
          command: init
          workingDirectory: "$(System.DefaultWorkingDirectory)/v2"
          backendType: selfConfigured
          commandOptions: -no-color -input=false
          allowTelemetryCollection: false

      - task: TerraformCLI@2
        displayName: "Terraform: plan"
        inputs:
          command: plan
          workingDirectory: "$(System.DefaultWorkingDirectory)/v2"
          commandOptions: -no-color -input=false
          allowTelemetryCollection: false
