trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: Terraform-Token

steps:
  - script: echo "##vso[task.setvariable variable=TF_TOKEN_app_terraform_io]$(TF_TOKEN)"
    displayName: "Terraform Token"

  - script: ls -al
    displayName: "Script: List files"
    workingDirectory: $(System.DefaultWorkingDirectory)/v2

  - task: TerraformInstaller@2
    displayName: "Terraform: Installer"
    inputs:
      terraformVersion: "latest"

  - task: TerraformCLI@2
    displayName: "Terraform: init"
    inputs:
      command: init
      workingDirectory: "$(System.DefaultWorkingDirectory)/v2"
      backendType: selfConfigured
      commandOptions: -no-color -input=false
      allowTelemetryCollection: false

  - task: TerraformCLI@2
    displayName: "Terraform: plan"
    inputs:
      command: plan
      workingDirectory: "$(System.DefaultWorkingDirectory)/v2"
      commandOptions: -no-color -input=false
      allowTelemetryCollection: false
