trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: Terraform-Token
  - name: TF_LOG
    value: INFO

steps:
  - script: echo "##vso[task.setvariable variable=TF_TOKEN_app_terraform_io]$(TF_TOKEN)"
    displayName: "Terraform Token"

  - task: TerraformInstaller@2
    inputs:
      terraformVersion: "latest"

  - task: TerraformCLI@2
    inputs:
      command: init
      workingDirectory: "$(System.DefaultWorkingDirectory)/v2"
      backendType: selfConfigured
      commandOptions: --input=false --no-color
      allowTelemetryCollection: false
