# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: Terraform-Token

steps:

- task: TerraformInstaller@2
  inputs:
    terraformVersion: 'latest'
    
- task: TerraformCLI@2
  inputs:
    command: init
    workingDirectory: '$(System.DefaultWorkingDirectory)/v2'
    backendType: selfConfigured
    commandOptions: --input=false --no-color
    allowTelemetryCollection: false