trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: Terraform-Token

jobs:
  - job: terraformv2
    displayName: "Terraform AzureRM 2.x"
    continueOnError: true # Errors are possible if resources have been upgraded to v3

    variables:
      TerraformSourceDirectory: $(System.DefaultWorkingDirectory)/v2
    steps:
      - script: echo "##vso[task.setvariable variable=TF_TOKEN_app_terraform_io]$(TF_TOKEN)"
        displayName: "Terraform Token"

      - task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@2
        displayName: "Terraform: Installer"
        inputs:
          terraformVersion: "latest"

      - task: TerraformCLI@2
        displayName: "Terraform: init"
        inputs:
          command: init
          workingDirectory: "$(TerraformSourceDirectory)"
          backendType: selfConfigured
          commandOptions: -no-color -input=false
          allowTelemetryCollection: false

      - task: TerraformCLI@2
        displayName: "Terraform: destroy"
        inputs:
          command: apply
          workingDirectory: "$(TerraformSourceDirectory)"
          commandOptions: -destroy -no-color -input=false -auto-approve
          allowTelemetryCollection: false

  - job: terraformv3
    displayName: "Terraform AzureRM 3.x"
    dependsOn: terraformv2
    condition: always()
    continueOnError: true # Errors are possible if resources not yet been upgraded to v3

    variables:
      TerraformSourceDirectory: $(System.DefaultWorkingDirectory)/v3
    steps:
      - script: echo "##vso[task.setvariable variable=TF_TOKEN_app_terraform_io]$(TF_TOKEN)"
        displayName: "Terraform Token"

      - task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@2
        displayName: "Terraform: Installer"
        inputs:
          terraformVersion: "latest"

      - task: TerraformCLI@2
        displayName: "Terraform: init"
        inputs:
          command: init
          workingDirectory: "$(TerraformSourceDirectory)"
          backendType: selfConfigured
          commandOptions: -no-color -input=false
          allowTelemetryCollection: false

      - task: TerraformCLI@2
        displayName: "Terraform: destroy"
        inputs:
          command: apply
          workingDirectory: "$(TerraformSourceDirectory)"
          commandOptions: -destroy -no-color -input=false -auto-approve
          allowTelemetryCollection: false
